-- Phase 2 — Core OLTP tables
-- Source of truth: docs/business-model.md §2
-- Currency: INR (₹). Naming: snake_case.
--
-- Load order (FK-safe): customers, sellers, products → inventory, orders → order_items
-- Idempotent: DROP + CREATE (full refresh friendly for early scaffold).

-- ── helpers ──────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- ── 2.1 customers ────────────────────────────────────────────────────────────
-- Grain: 1 row per customer · 603,815 rows

DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.inventory CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.sellers CASCADE;
DROP TABLE IF EXISTS public.customers CASCADE;

CREATE TABLE public.customers (
  customer_id         TEXT        PRIMARY KEY,          -- source user_id (e.g. U356787)
  home_city           TEXT        NOT NULL,             -- mode of locations; ties → most recent
  first_purchase_date DATE        NOT NULL,             -- MIN(order_date)
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_customers_updated_at
  BEFORE UPDATE ON public.customers
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

COMMENT ON TABLE public.customers IS
  'Marketplace buyers. home_city is derived (mode of ship-to cities).';

-- ── 2.2 sellers ──────────────────────────────────────────────────────────────
-- Grain: 1 row per seller · 9,000 rows

CREATE TABLE public.sellers (
  seller_id       TEXT           PRIMARY KEY,           -- source seller_id (e.g. S2679)
  current_rating  NUMERIC(2, 1)  NOT NULL
                    CHECK (current_rating >= 0.0 AND current_rating <= 5.0),
  created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_sellers_updated_at
  BEFORE UPDATE ON public.sellers
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

COMMENT ON TABLE public.sellers IS
  'Independent marketplace sellers. current_rating = latest snapshot at max(order_date).';
COMMENT ON COLUMN public.sellers.current_rating IS
  'Latest seller_rating (0.0–5.0). History lives in order_items.seller_rating_at_sale.';

-- ── 2.3 products ─────────────────────────────────────────────────────────────
-- Grain: 1 row per product · 89,999 rows

CREATE TABLE public.products (
  product_id      TEXT           PRIMARY KEY,           -- source product_id (e.g. P39256)
  category        TEXT           NOT NULL
                    CHECK (category IN (
                      'Electronics', 'Home', 'Sports', 'Beauty', 'Clothing'
                    )),
  subcategory     TEXT           NOT NULL,
  brand           TEXT           NOT NULL,
  current_price   NUMERIC(10, 2) NOT NULL
                    CHECK (current_price > 0),
  product_rating  NUMERIC(2, 1)  NOT NULL
                    CHECK (product_rating >= 0.0 AND product_rating <= 5.0),
  review_count    INTEGER        NOT NULL DEFAULT 0
                    CHECK (review_count >= 0),
  created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE INDEX idx_products_category ON public.products (category);
CREATE INDEX idx_products_brand    ON public.products (brand);

CREATE TRIGGER trg_products_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

COMMENT ON TABLE public.products IS
  'Catalog. current_price / product_rating / review_count are latest snapshots; sale prices live in order_items.';
COMMENT ON COLUMN public.products.current_price IS
  'Latest observed price (₹). Historical prices: order_items.unit_price.';

-- ── 2.4 inventory ────────────────────────────────────────────────────────────
-- Grain: 1 row per product per observed date (stock snapshots)

CREATE TABLE public.inventory (
  inventory_id  BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id    TEXT    NOT NULL REFERENCES public.products (product_id),
  snapshot_date DATE    NOT NULL,
  stock         INTEGER NOT NULL CHECK (stock >= 0 AND stock <= 500),
  CONSTRAINT uq_inventory_product_date UNIQUE (product_id, snapshot_date)
);

CREATE INDEX idx_inventory_product_date
  ON public.inventory (product_id, snapshot_date DESC);

COMMENT ON TABLE public.inventory IS
  'Per-product stock snapshots. Stock-critical KPI: latest stock < 20. UNIQUE enables idempotent re-ingestion.';

-- ── 2.5 orders ───────────────────────────────────────────────────────────────
-- Grain: 1 row per order · 1,000,000 rows
-- delivery_status is the single source of truth for fulfillment (§3).
-- Contract values (normalized from source Title Case in Phase 3):
--   IN TRANSIT → {DELIVERED, DELAYED, RETURNED}; terminal states immutable.

CREATE TABLE public.orders (
  order_id            BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id         TEXT    NOT NULL REFERENCES public.customers (customer_id),
  order_date          DATE    NOT NULL,
  ship_to_city        TEXT    NOT NULL,
  payment_method      TEXT    NOT NULL
                        CHECK (payment_method IN (
                          'UPI', 'Credit Card', 'Debit Card', 'Cash on Delivery'
                        )),
  device              TEXT    NOT NULL
                        CHECK (device IN ('Mobile App', 'Web', 'Tablet')),
  delivery_status     TEXT    NOT NULL
                        CHECK (delivery_status IN (
                          'IN TRANSIT', 'DELIVERED', 'DELAYED', 'RETURNED'
                        )),
  shipping_time_days  SMALLINT NOT NULL
                        CHECK (shipping_time_days BETWEEN 1 AND 6),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_orders_customer   ON public.orders (customer_id);
CREATE INDEX idx_orders_date       ON public.orders (order_date);
CREATE INDEX idx_orders_status     ON public.orders (delivery_status);
CREATE INDEX idx_orders_city       ON public.orders (ship_to_city);
CREATE INDEX idx_orders_date_status ON public.orders (order_date, delivery_status);

CREATE TRIGGER trg_orders_updated_at
  BEFORE UPDATE ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

COMMENT ON TABLE public.orders IS
  'One marketplace order. Source CSV has no order id — each source row = one order (seed is 1:1 with order_items).';
COMMENT ON COLUMN public.orders.delivery_status IS
  'Fulfillment SoT. Lifecycle: IN TRANSIT → {DELIVERED, DELAYED, RETURNED}. Terminal states immutable (Phase 4).';
COMMENT ON COLUMN public.orders.ship_to_city IS
  'Per-order ship-to city (39% of customers use multiple cities). Not a customer attribute.';

-- ── 2.6 order_items ──────────────────────────────────────────────────────────
-- Grain: 1 row per order line
-- Seed data is 1:1 with orders; schema supports multi-item / multi-qty (Phase 4).
-- final_price invariant: final_price ≈ unit_price × quantity × (1 − discount_pct/100)
-- Source round-trips at up to ~₹4 (high-precision source rounded twice).
-- Tolerance ₹5.00 covers 100% of the 1M seed rows while still catching real errors.

CREATE TABLE public.order_items (
  order_item_id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id               BIGINT         NOT NULL REFERENCES public.orders (order_id),
  product_id             TEXT           NOT NULL REFERENCES public.products (product_id),
  seller_id              TEXT           NOT NULL REFERENCES public.sellers (seller_id),
  quantity               SMALLINT       NOT NULL DEFAULT 1
                           CHECK (quantity >= 1),
  unit_price             NUMERIC(10, 2) NOT NULL
                           CHECK (unit_price > 0),
  discount_pct           NUMERIC(4, 2)  NOT NULL DEFAULT 0
                           CHECK (discount_pct >= 0 AND discount_pct <= 70),
  final_price            NUMERIC(10, 2) NOT NULL
                           CHECK (final_price >= 0),
  seller_rating_at_sale  NUMERIC(2, 1)  NOT NULL
                           CHECK (seller_rating_at_sale >= 0.0 AND seller_rating_at_sale <= 5.0),
  CONSTRAINT chk_order_items_final_price CHECK (
    abs(
      final_price
      - round(unit_price * quantity * (1 - discount_pct / 100), 2)
    ) <= 5.00
  )
);

CREATE INDEX idx_order_items_order   ON public.order_items (order_id);
CREATE INDEX idx_order_items_product ON public.order_items (product_id);
CREATE INDEX idx_order_items_seller  ON public.order_items (seller_id);

COMMENT ON TABLE public.order_items IS
  'Order lines. final_price = unit_price × qty × (1 − discount_pct/100), CHECK ±₹5.00.';
COMMENT ON COLUMN public.order_items.unit_price IS
  'Price snapshot at time of sale (₹). Distinct from products.current_price.';
COMMENT ON COLUMN public.order_items.seller_rating_at_sale IS
  'Seller quality snapshot at sale — preserves history for top-sellers KPI.';
COMMENT ON COLUMN public.order_items.final_price IS
  'What the customer paid (₹). Gross revenue = Σ final_price. No COGS in source; est. unit_cost = 0.65 × unit_price.';
