-- Phase 4 — Append-only audit trail for state-changing API operations.
-- Contract: docs/business-model.md §3 (atomic transitions with audit logging).
--
-- One row per mutation, written in the SAME transaction as the change, so a
-- rollback erases both — the log never claims uncommitted work.
-- Mirrored in SQLAlchemy (backend/app/models/entities.py AuditLog) and the
-- Alembic initial revision; all three produce the same schema.

CREATE TABLE IF NOT EXISTS public.audit_log (
  audit_id    BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  actor       VARCHAR(64) NOT NULL DEFAULT 'api',
  table_name  TEXT    NOT NULL,
  row_pk      TEXT    NOT NULL,
  action      TEXT    NOT NULL
                CHECK (action IN ('insert', 'update', 'delete')),
  details     JSONB
);

CREATE INDEX IF NOT EXISTS idx_audit_table_row ON public.audit_log (table_name, row_pk);
CREATE INDEX IF NOT EXISTS idx_audit_at ON public.audit_log (at);

COMMENT ON TABLE public.audit_log IS
  'Append-only audit trail. Written in-transaction with each mutation (Phase 4).';
