-- Phase 8 — Batch revenue forecasts (RF primary, Prophet second opinion).
-- Contract: notebooks/04_forecasting.ipynb (RF 3.38% / Prophet 3.96% MAPE,
-- rolling 90d). Writers: backend forecast refresh job ONLY (full refresh per
-- model, UNIQUE on (model, target_date) makes reruns idempotent).
-- Readers: GET /stats/forecast → Overview projection overlay.

CREATE TABLE IF NOT EXISTS public.revenue_forecasts (
  forecast_id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asof_date   DATE    NOT NULL,   -- last data date seen by the fit
  target_date DATE    NOT NULL,   -- the day being predicted
  model       TEXT    NOT NULL
                CHECK (model IN ('rf', 'prophet')),
  horizon_d   INTEGER NOT NULL CHECK (horizon_d >= 1),
  yhat        NUMERIC(14, 2) NOT NULL CHECK (yhat >= 0),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_forecast_model_target UNIQUE (model, target_date)
);

CREATE INDEX IF NOT EXISTS idx_forecasts_target ON public.revenue_forecasts (target_date);

COMMENT ON TABLE public.revenue_forecasts IS
  'Batch daily-revenue forecasts. RF ships (lowest MAPE); Prophet is the interpretable second opinion. Never a substitute for actuals.';
