-- Phase 9 — Document attachments for grounded insights.
-- Users attach business documents (reports, policies, reviews CSVs) in the web
-- app; bytes live in the `workspace.bronze.documents` UC Volume, registry +
-- text chunks + local embeddings live here (retrieval in Python cosine;
-- Vector Search index only if scale justifies it — see docs/decisions.md).
-- Embeddings are JSONB float arrays (pgvector retired as sidecar; at tens to
-- hundreds of docs brute-force cosine is exact and dependency-free).

CREATE TABLE IF NOT EXISTS public.documents (
  document_id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename    TEXT    NOT NULL,
  mime_type   TEXT    NOT NULL
                CHECK (mime_type IN ('application/pdf', 'text/markdown',
                                     'text/plain', 'text/csv')),
  size_bytes  INTEGER NOT NULL CHECK (size_bytes > 0 AND size_bytes <= 20 * 1024 * 1024),
  volume_path TEXT    UNIQUE,   -- NULL while pending; filled on store put
  status      TEXT    NOT NULL DEFAULT 'uploaded'
                CHECK (status IN ('uploaded', 'ready', 'failed')),
  error       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.document_chunks (
  chunk_id    BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT  NOT NULL REFERENCES public.documents (document_id) ON DELETE CASCADE,
  chunk_index INTEGER NOT NULL CHECK (chunk_index >= 0),
  content     TEXT    NOT NULL,
  embedding   JSONB,   -- NULL until embedded; float array, all-MiniLM-L6-v2 (384d)
  CONSTRAINT uq_chunk_doc_idx UNIQUE (document_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_chunks_document ON public.document_chunks (document_id);

COMMENT ON TABLE public.documents IS
  'User-attached business documents. Bytes in UC Volume; text+vectors here for grounded insights (Phase 9).';
COMMENT ON COLUMN public.document_chunks.embedding IS
  'Local sentence-transformer embedding (384d). NULL = not yet embedded.';
