#!/usr/bin/env python3
"""Phase 3 — Seed ingestion.

Loads the 1M-row Amazon-style dataset into PostgreSQL:

    CSV ──COPY──► raw.purchases (all TEXT, 1:1 columns)
        ──validate──► staging.purchases (typed, trimmed, normalized enums)
        ──normalize──► customers · sellers · products · inventory · orders · order_items

Contract: docs/business-model.md §6. Idempotent full refresh.

Usage:
    ./scripts/seed/ingest.py [--csv PATH] [--conn "...dsn..."]
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import psycopg2

REPO = Path(__file__).resolve().parents[2]
DEFAULT_CSV = REPO / "data/amazon-e-commerce/amazon_ecommerce_1M.csv"


def default_dsn() -> str:
    host = os.environ.get("PGHOST", "uptown")
    port = os.environ.get("PGPORT", "5432")
    user = os.environ.get("PGUSER", "magrey")
    database = os.environ.get("PGDATABASE", "smart")
    password = os.environ.get("PGPASSWORD", "")
    return f"host={host} port={port} user={user} dbname={database} password={password}"


def load_csv(cur, csv_path: Path) -> int:
    """COPY the CSV into raw.purchases. Returns number of rows loaded."""
    cur.execute("DELETE FROM raw.purchases;")
    with open(csv_path, "rb") as f:
        cur.copy_expert(
            """COPY raw.purchases (
                user_id, product_id, category, subcategory, brand, price, discount,
                final_price, rating, review_count, stock, seller_id, seller_rating,
                purchase_date, shipping_time_days, location, device, payment_method,
                is_returned, delivery_status
            ) FROM STDIN WITH (FORMAT csv, HEADER true)
            """,
            f,
        )
    cur.execute("SELECT count(*) FROM raw.purchases;")
    return cur.fetchone()[0]


def load_staging(cur) -> int:
    """Typed, trimmed, enum-normalized intermediate between raw and core tables."""
    cur.execute("DELETE FROM staging.purchases;")
    cur.execute(
        """
        INSERT INTO staging.purchases (
          user_id, product_id, category, subcategory, brand,
          price, discount, final_price, rating, review_count, stock,
          seller_id, seller_rating, purchase_date, shipping_time_days,
          location, device, payment_method, delivery_status
        )
        SELECT
          btrim(user_id), btrim(product_id), btrim(category), btrim(subcategory), btrim(brand),
          round(price::numeric, 2), round(discount::numeric, 2), round(final_price::numeric, 2),
          round(rating::numeric, 1), review_count::int, stock::int,
          btrim(seller_id), round(seller_rating::numeric, 2),
          purchase_date::date, shipping_time_days::smallint,
          btrim(location), btrim(device), btrim(payment_method),
          -- normalize source Title Case ("In Transit") -> contract UPPER ("IN TRANSIT")
          upper(btrim(delivery_status))
        FROM raw.purchases;
        """
    )
    cur.execute("SELECT count(*) FROM staging.purchases;")
    return cur.fetchone()[0]


def normalize(cur) -> None:
    """Split the typed event stream into the six normalized core tables.

    Load order is FK-safe: customers, sellers, products -> inventory, orders -> order_items.

    orders/order_items are 1:1 with the source stream (seed). We materialize a
    deterministic row surrogate on staging and drive BOTH orders.order_id and
    order_items.order_id from it, so the pairing never depends on insert order,
    identity gaps, or parallelism — fully reproducible and idempotent.

    order_id is GENERATED BY DEFAULT AS IDENTITY, so we can supply explicit
    surrogate values while still falling back to the sequence for Phase-4 rows.
    """
    # Deterministic per-row surrogate over the event stream.
    cur.execute("ALTER TABLE staging.purchases ADD COLUMN IF NOT EXISTS row_idx BIGINT;")
    cur.execute(
        """
        WITH numbered AS (
          SELECT ctid, row_number() OVER (ORDER BY purchase_date, user_id, product_id) AS rn
          FROM staging.purchases
        )
        UPDATE staging.purchases s
        SET row_idx = numbered.rn
        FROM numbered
        WHERE numbered.ctid = s.ctid;
        """
    )

    # ── Clear (FK-safe: children before parents) ──────────────────────────────
    # Deletes MUST run children-first or Postgres raises FK violations on re-run.
    cur.execute("DELETE FROM public.order_items;")
    cur.execute("DELETE FROM public.orders;")
    cur.execute("DELETE FROM public.inventory;")
    cur.execute("DELETE FROM public.products;")
    cur.execute("DELETE FROM public.sellers;")
    cur.execute("DELETE FROM public.customers;")
    # Reset identities so a full refresh produces byte-identical data on every run.
    cur.execute("ALTER TABLE public.orders      ALTER COLUMN order_id      RESTART WITH 1;")
    cur.execute("ALTER TABLE public.order_items ALTER COLUMN order_item_id RESTART WITH 1;")

    # ── customers: home_city = mode of locations; ties -> most recent order ────
    cur.execute(
        """
        WITH ranked AS (
          SELECT
            user_id,
            location,
            purchase_date,
            row_number() OVER (PARTITION BY user_id ORDER BY cnt DESC, purchase_date DESC) AS rn
          FROM (
            SELECT user_id, location, max(purchase_date) AS purchase_date, count(*) AS cnt
            FROM staging.purchases
            GROUP BY user_id, location
          ) s
        )
        INSERT INTO public.customers (customer_id, home_city, first_purchase_date)
        SELECT
          s.user_id,
          r.location,
          min(s.purchase_date)
        FROM (
            SELECT user_id, min(purchase_date) AS purchase_date
            FROM staging.purchases GROUP BY user_id
        ) s
        JOIN ranked r ON r.user_id = s.user_id AND r.rn = 1
        GROUP BY s.user_id, r.location;
        """
    )

    # ── customers (mode of locations; ties -> most recent) ─────────────────────
    cur.execute(
        """
        INSERT INTO public.sellers (seller_id, current_rating)
        SELECT seller_id, seller_rating
        FROM (
          SELECT seller_id, seller_rating,
                 row_number() OVER (PARTITION BY seller_id ORDER BY purchase_date DESC) AS rn
          FROM staging.purchases
        ) ranked
        WHERE rn = 1;
        """
    )

    # --- products: latest snapshot per product ---
    cur.execute(
        """
        INSERT INTO public.products
          (product_id, category, subcategory, brand, current_price, product_rating, review_count)
        SELECT product_id, category, subcategory, brand, price, rating, review_count
        FROM (
          SELECT product_id, category, subcategory, brand, price, rating, review_count,
                 row_number() OVER (PARTITION BY product_id ORDER BY purchase_date DESC) AS rn
          FROM staging.purchases
        ) ranked
        WHERE rn = 1;
        """
    )

    # --- inventory: distinct (product_id, purchase_date, stock); last stock on same-date wins ---
    cur.execute(
        """
        INSERT INTO public.inventory (product_id, snapshot_date, stock)
        SELECT DISTINCT ON (product_id, purchase_date) product_id, purchase_date, stock
        FROM staging.purchases
        ORDER BY product_id, purchase_date;
        """
    )

    # --- orders: one order per source row (seed is 1:1 with order_items) ---
    # Supply explicit identifier = source surrogate; identity sequences advance in Phase-4 only.
    cur.execute(
        """
        INSERT INTO public.orders
          (order_id, customer_id, order_date, ship_to_city, payment_method, device,
           delivery_status, shipping_time_days)
        SELECT
          row_idx, user_id, purchase_date, location, payment_method, device,
          delivery_status, shipping_time_days
        FROM staging.purchases
        ORDER BY row_idx;
        """
    )

    # --- order_items: one line per order, paired by the shared surrogate ---
    cur.execute(
        """
        INSERT INTO public.order_items
          (order_id, product_id, seller_id, quantity, unit_price,
           discount_pct, final_price, seller_rating_at_sale)
        SELECT
          row_idx, product_id, seller_id, 1, price,
          discount, final_price, seller_rating
        FROM staging.purchases
        ORDER BY row_idx;
        """
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--csv", default=str(DEFAULT_CSV), help="path to 1M-row CSV")
    ap.add_argument("--dsn", default=default_dsn(), help="postgres DSN")
    args = ap.parse_args()

    csv_path = Path(args.csv)
    if not csv_path.exists():
        print(f"ERROR: CSV not found: {csv_path}", file=sys.stderr)
        return 1

    conn = psycopg2.connect(args.dsn)
    try:
        with conn, conn.cursor() as cur:
            raw_n = load_csv(cur, csv_path)
            stg_n = load_staging(cur)
            normalize(cur)
            conn.commit()
        print(f"raw: {raw_n}  staging: {stg_n}")
        print("Normalization complete.")
    finally:
        conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())