#!/usr/bin/env python3
"""Phase 3 — Seed ingestion (stdlib only, no third-party deps).

Loads the 1M-row Amazon-style dataset into PostgreSQL:

    CSV ──COPY──► raw.purchases (all TEXT, 1:1 columns)
        ──validate──► staging.purchases (typed, trimmed, normalized enums)
        ──normalize──► customers · sellers · products · inventory · orders · order_items

Contract: docs/business-model.md §6. Idempotent full refresh.

Connection uses the standard libpq env vars (same as database/apply.sh):
    PGHOST / PGPORT / PGUSER / PGPASSWORD / PGDATABASE
Bulk load goes through the ``psql`` CLI (``\\copy``), so this script needs
no database driver — ``psql`` must be on PATH.

Usage:
    python3 scripts/seed/ingest.py [--csv PATH]
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DEFAULT_CSV = REPO / "data/amazon-e-commerce/amazon_ecommerce_1M.csv"

RAW_COPY_COLUMNS = (
    "user_id, product_id, category, subcategory, brand, price, discount,"
    " final_price, rating, review_count, stock, seller_id, seller_rating,"
    " purchase_date, shipping_time_days, location, device, payment_method,"
    " is_returned, delivery_status"
)


def run_psql(args: list[str], sql: str) -> str:
    """Run one psql statement. Raises on error (ON_ERROR_STOP=1)."""
    proc = subprocess.run(
        ["psql", "-X", "-q", "-v", "ON_ERROR_STOP=1", *args, "-c", sql],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        print(proc.stderr.strip(), file=sys.stderr)
        raise SystemExit(f"psql failed (exit {proc.returncode})")
    return proc.stdout.strip()


def scalar(sql: str) -> str:
    """Run a query returning a single value (no headers, unaligned)."""
    return run_psql(["-At"], sql)


def load_csv(csv_path: Path) -> int:
    """COPY the CSV into raw.purchases. Returns rows loaded."""
    quoted = str(csv_path).replace("'", "''")
    run_psql([], "DELETE FROM raw.purchases;")
    run_psql([], f"\\copy raw.purchases ({RAW_COPY_COLUMNS}) FROM '{quoted}' WITH (FORMAT csv, HEADER true)")
    return int(scalar("SELECT count(*) FROM raw.purchases;"))


def load_staging() -> int:
    """Typed, trimmed, enum-normalized intermediate between raw and core tables."""
    run_psql([], "DELETE FROM staging.purchases;")
    run_psql(
        [],
        """
        INSERT INTO staging.purchases (
          user_id, product_id, category, subcategory, brand,
          price, discount, final_price, rating, review_count, stock,
          seller_id, seller_rating, purchase_date, shipping_time_days,
          location, device, payment_method, delivery_status
        )
        SELECT
          btrim(user_id), btrim(product_id), btrim(category), btrim(subcategory), btrim(brand),
          round(price::numeric, 2), round(discount::numeric, 2), round(final_price::numeric, 2),
          round(rating::numeric, 1), review_count::int, stock::int,
          btrim(seller_id), round(seller_rating::numeric, 2),
          purchase_date::date, shipping_time_days::smallint,
          btrim(location), btrim(device), btrim(payment_method),
          -- normalize source Title Case ("In Transit") -> contract UPPER ("IN TRANSIT")
          upper(btrim(delivery_status))
        FROM raw.purchases;
        """,
    )
    return int(scalar("SELECT count(*) FROM staging.purchases;"))


def normalize() -> None:
    """Split the typed event stream into the six normalized core tables.

    Load order is FK-safe: customers, sellers, products -> inventory,
    orders -> order_items.

    orders/order_items are 1:1 with the source stream (seed). We materialize
    a deterministic row surrogate on staging and drive BOTH orders.order_id
    and order_items.order_id from it, so the pairing never depends on insert
    order, identity gaps, or parallelism — fully reproducible and idempotent.

    order_id is GENERATED BY DEFAULT AS IDENTITY, so we can supply explicit
    surrogate values while still falling back to the sequence for Phase-4 rows.
    """
    # Deterministic per-row surrogate over the event stream.
    run_psql([], "ALTER TABLE staging.purchases ADD COLUMN IF NOT EXISTS row_idx BIGINT;")
    run_psql(
        [],
        """
        WITH numbered AS (
          SELECT ctid, row_number() OVER (ORDER BY purchase_date, user_id, product_id) AS rn
          FROM staging.purchases
        )
        UPDATE staging.purchases s
        SET row_idx = numbered.rn
        FROM numbered
        WHERE numbered.ctid = s.ctid;
        """,
    )

    # ── Clear (FK-safe: children before parents) ──────────────────────────
    # Deletes MUST run children-first or Postgres raises FK violations on re-run.
    run_psql([], "DELETE FROM public.order_items;")
    run_psql([], "DELETE FROM public.orders;")
    run_psql([], "DELETE FROM public.inventory;")
    run_psql([], "DELETE FROM public.products;")
    run_psql([], "DELETE FROM public.sellers;")
    run_psql([], "DELETE FROM public.customers;")
    # Reset identities so a full refresh produces identical IDs on every run.
    run_psql([], "ALTER TABLE public.orders ALTER COLUMN order_id RESTART WITH 1;")
    run_psql([], "ALTER TABLE public.order_items ALTER COLUMN order_item_id RESTART WITH 1;")

    # ── customers: home_city = mode of locations; ties -> most recent order ──
    run_psql(
        [],
        """
        WITH ranked AS (
          SELECT
            user_id,
            location,
            purchase_date,
            row_number() OVER (PARTITION BY user_id ORDER BY cnt DESC, purchase_date DESC) AS rn
          FROM (
            SELECT user_id, location, max(purchase_date) AS purchase_date, count(*) AS cnt
            FROM staging.purchases
            GROUP BY user_id, location
          ) s
        )
        INSERT INTO public.customers (customer_id, home_city, first_purchase_date)
        SELECT
          s.user_id,
          r.location,
          min(s.purchase_date)
        FROM (
            SELECT user_id, min(purchase_date) AS purchase_date
            FROM staging.purchases GROUP BY user_id
        ) s
        JOIN ranked r ON r.user_id = s.user_id AND r.rn = 1
        GROUP BY s.user_id, r.location;
        """,
    )

    # ── sellers: latest rating snapshot per seller ──────────────────────────
    run_psql(
        [],
        """
        INSERT INTO public.sellers (seller_id, current_rating)
        SELECT seller_id, seller_rating
        FROM (
          SELECT seller_id, seller_rating,
                 row_number() OVER (PARTITION BY seller_id ORDER BY purchase_date DESC) AS rn
          FROM staging.purchases
        ) ranked
        WHERE rn = 1;
        """,
    )

    # ── products: latest snapshot per product ───────────────────────────────
    run_psql(
        [],
        """
        INSERT INTO public.products
          (product_id, category, subcategory, brand, current_price, product_rating, review_count)
        SELECT product_id, category, subcategory, brand, price, rating, review_count
        FROM (
          SELECT product_id, category, subcategory, brand, price, rating, review_count,
                 row_number() OVER (PARTITION BY product_id ORDER BY purchase_date DESC) AS rn
          FROM staging.purchases
        ) ranked
        WHERE rn = 1;
        """,
    )

    # ── inventory: distinct (product_id, purchase_date, stock) ──────────────
    run_psql(
        [],
        """
        INSERT INTO public.inventory (product_id, snapshot_date, stock)
        SELECT DISTINCT ON (product_id, purchase_date) product_id, purchase_date, stock
        FROM staging.purchases
        ORDER BY product_id, purchase_date;
        """,
    )

    # ── orders: one order per source row (seed is 1:1 with order_items) ──────
    # Supply explicit identifier = source surrogate; sequences advance in Phase 4 only.
    run_psql(
        [],
        """
        INSERT INTO public.orders
          (order_id, customer_id, order_date, ship_to_city, payment_method, device,
           delivery_status, shipping_time_days)
        SELECT
          row_idx, user_id, purchase_date, location, payment_method, device,
          delivery_status, shipping_time_days
        FROM staging.purchases
        ORDER BY row_idx;
        """,
    )

    # ── order_items: one line per order, paired by the shared surrogate ─────
    run_psql(
        [],
        """
        INSERT INTO public.order_items
          (order_id, product_id, seller_id, quantity, unit_price,
           discount_pct, final_price, seller_rating_at_sale)
        SELECT
          row_idx, product_id, seller_id, 1, price,
          discount, final_price, seller_rating
        FROM staging.purchases
        ORDER BY row_idx;
        """,
    )


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--csv", default=str(DEFAULT_CSV), help="path to 1M-row CSV")
    args = ap.parse_args()

    if shutil.which("psql") is None:
        print("ERROR: `psql` not found on PATH (PostgreSQL client required).", file=sys.stderr)
        return 1

    csv_path = Path(args.csv)
    if not csv_path.exists():
        print(f"ERROR: CSV not found: {csv_path}", file=sys.stderr)
        return 1

    raw_n = load_csv(csv_path)
    print(f"raw: {raw_n}")
    stg_n = load_staging()
    print(f"staging: {stg_n}")
    normalize()
    print("Normalization complete.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
